//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Programmesana_Sanija_Airita.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upload
    {
        public int id { get; set; }
        public string Path { get; set; }
        public System.Guid File_id { get; set; }
    
        public virtual File File { get; set; }
    }
}
